### ISSUE TITLE
Testing for elasticsearch

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/chart-elasticsearch#10]
Set up tests for chart-elasticsearch. 
This will involve researching unit tests for elasticsearch.
[Here](https://www.elastic.co/blog/elasticsearch-testing-qa-increasing-coverage-randomizing-test-runs) are some articles of possible interest (link is the final article of a three part series; the first two articles are linked in the first paragraph).

**Comment by coffeepac** [comment]
waiting for conversion to CI

helm linting and deploy into a fresh namespace int he Gitlan kubnerets cluterrstss

**Comment by mikeln** [comment]
Superceeded by conversion to new jenkins
